import React from "react";
import {
  Tv,
  Music,
  Play,
  Star,
  Palette,
  Code,
  FileText,
  MessageSquare,
  PenTool,
  Bot,
  Cloud,
  Heart,
  Dumbbell,
  Headphones,
  ShoppingCart,
  Briefcase,
  BookOpen,
  Wrench,
  Globe,
  Camera,
  Gamepad2,
  CreditCard,
  Shield,
  Server,
  Database,
  Figma,
  Rocket,
  Newspaper,
  Car,
  Home,
  Wifi,
  Phone,
  Video,
  Mic,
  MoreHorizontal,
  Calendar,
} from "lucide-react";

const SERVICE_ICONS = {
  netflix: Tv,
  spotify: Music,
  "youtube premium": Play,
  youtube: Play,
  "disney+": Star,
  "disney plus": Star,
  hulu: Tv,
  "hbo max": Tv,
  hbo: Tv,
  "amazon prime": ShoppingCart,
  "apple tv+": Tv,
  "apple music": Music,
  "adobe creative cloud": Palette,
  adobe: Palette,
  photoshop: Palette,
  "github pro": Code,
  github: Code,
  gitlab: Code,
  notion: FileText,
  slack: MessageSquare,
  figma: PenTool,
  "chatgpt plus": Bot,
  chatgpt: Bot,
  openai: Bot,
  midjourney: Bot,
  aws: Cloud,
  "gym membership": Dumbbell,
  gym: Dumbbell,
  fitness: Heart,
  peloton: Dumbbell,
  headspace: Headphones,
  calm: Headphones,
  duolingo: BookOpen,
  udemy: BookOpen,
  coursera: BookOpen,
  masterclass: BookOpen,
  skillshare: BookOpen,
  dropbox: Database,
  "google drive": Database,
  "google one": Database,
  icloud: Cloud,
  "microsoft 365": Briefcase,
  "office 365": Briefcase,
  zoom: Video,
  nordvpn: Shield,
  expressvpn: Shield,
  vpn: Shield,
  evernote: FileText,
  todoist: FileText,
  clickup: FileText,
  asana: FileText,
  trello: FileText,
  linear: Figma,
  canva: PenTool,
  pinterest: Globe,
  "twitter x": Globe,
  twitter: Globe,
  reddit: Globe,
  twitch: Gamepad2,
  "xbox game pass": Gamepad2,
  "playstation plus": Gamepad2,
  "nintendo online": Gamepad2,
  "discord nitro": MessageSquare,
  discord: MessageSquare,
  patreon: Heart,
  substack: Newspaper,
  medium: FileText,
  strava: Dumbbell,
  myfitnesspal: Heart,
  doordash: ShoppingCart,
  "uber one": Car,
  "hello fresh": ShoppingCart,
  "blue apron": ShoppingCart,
  "spotify family": Music,
  tidal: Music,
  deezer: Music,
  pandora: Music,
  "prime video": Tv,
  peacock: Tv,
  "paramount+": Tv,
  "paramount plus": Tv,
  crunchyroll: Tv,
  funimation: Tv,
  dazn: Tv,
  "espn+": Tv,
  "mlb tv": Tv,
  "nba league pass": Tv,
  internet: Wifi,
  phone: Phone,
  "phone plan": Phone,
  electricity: Cloud,
  water: Cloud,
  rent: Home,
  mortgage: Home,
  insurance: Shield,
  "cloud storage": Cloud,
  "web hosting": Server,
  domain: Globe,
  ssl: Shield,
  backup: Database,
  ring: Camera,
  nest: Home,
  arlo: Camera,
  grammarly: PenTool,
  quillbot: PenTool,
  "1password": Shield,
  lastpass: Shield,
  dashlane: Shield,
  bitwarden: Shield,
  "monday.com": Briefcase,
  salesforce: Briefcase,
  hubspot: Briefcase,
  zapier: Rocket,
  make: Rocket,
  airtable: Database,
  typeform: FileText,
  webflow: Globe,
  wix: Globe,
  squarespace: Globe,
  shopify: ShoppingCart,
  stripe: CreditCard,
  wave: CreditCard,
  quickbooks: Briefcase,
  xero: Briefcase,
  freshbooks: Briefcase,
  calendly: Calendar,
  "zoom info": Video,
  loom: Video,
  vimeo: Video,
  wistia: Video,
  sentry: Wrench,
  datadog: Server,
  "new relic": Server,
  vercel: Rocket,
  netlify: Rocket,
  heroku: Cloud,
  digitalocean: Cloud,
  render: Cloud,
  railway: Cloud,
  "fly.io": Rocket,
  supabase: Database,
  firebase: Database,
  planetscale: Database,
  neon: Database,
};

export default function SubscriptionLogo({ name, color, size = "md" }) {
  const sizes = {
    sm: { container: "w-8 h-8 rounded-lg", iconSize: "w-3.5 h-3.5" },
    md: { container: "w-11 h-11 rounded-xl", iconSize: "w-5 h-5" },
    lg: { container: "w-14 h-14 rounded-2xl", iconSize: "w-6 h-6" },
  };

  const { container, iconSize } = sizes[size] || sizes.md;

  const lowerName = (name || "").toLowerCase().trim();
  const iconKey = Object.keys(SERVICE_ICONS).find((key) =>
    lowerName.includes(key),
  );
  const IconComponent = iconKey ? SERVICE_ICONS[iconKey] : null;

  return (
    <div
      className={`${container} flex items-center justify-center text-white font-bold shadow-lg shrink-0`}
      style={{ backgroundColor: color || "#8b8b8b" }}
    >
      {IconComponent ? (
        <IconComponent className={iconSize} strokeWidth={2} />
      ) : (
        <span className="text-sm">{name?.charAt(0)?.toUpperCase() || "?"}</span>
      )}
    </div>
  );
}
